/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InitRouteImport } from './routes/init'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as RoutesNewRouteImport } from './routes/routes/new'
import { Route as RoutesRouteIdRouteImport } from './routes/routes/$routeId'
import { Route as RoutesRouteIdIndexRouteImport } from './routes/routes/$routeId.index'
import { Route as RoutesRouteIdEditRouteImport } from './routes/routes/$routeId.edit'

const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdIndexRoute = RoutesRouteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutesRouteIdRoute,
} as any)
const RoutesRouteIdEditRoute = RoutesRouteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RoutesRouteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/routes/$routeId': typeof RoutesRouteIdRouteWithChildren
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
  '/routes/$routeId/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId/': typeof RoutesRouteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
  '/routes/$routeId/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId': typeof RoutesRouteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/error': typeof ErrorRoute
  '/init': typeof InitRoute
  '/routes/$routeId': typeof RoutesRouteIdRouteWithChildren
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
  '/routes/$routeId/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId/': typeof RoutesRouteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/error'
    | '/init'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes'
    | '/routes/$routeId/edit'
    | '/routes/$routeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/error'
    | '/init'
    | '/routes/new'
    | '/routes'
    | '/routes/$routeId/edit'
    | '/routes/$routeId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/error'
    | '/init'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
    | '/routes/$routeId/edit'
    | '/routes/$routeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ErrorRoute: typeof ErrorRoute
  InitRoute: typeof InitRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRouteWithChildren
  RoutesNewRoute: typeof RoutesNewRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId/': {
      id: '/routes/$routeId/'
      path: '/'
      fullPath: '/routes/$routeId/'
      preLoaderRoute: typeof RoutesRouteIdIndexRouteImport
      parentRoute: typeof RoutesRouteIdRoute
    }
    '/routes/$routeId/edit': {
      id: '/routes/$routeId/edit'
      path: '/edit'
      fullPath: '/routes/$routeId/edit'
      preLoaderRoute: typeof RoutesRouteIdEditRouteImport
      parentRoute: typeof RoutesRouteIdRoute
    }
  }
}

interface RoutesRouteIdRouteChildren {
  RoutesRouteIdEditRoute: typeof RoutesRouteIdEditRoute
  RoutesRouteIdIndexRoute: typeof RoutesRouteIdIndexRoute
}

const RoutesRouteIdRouteChildren: RoutesRouteIdRouteChildren = {
  RoutesRouteIdEditRoute: RoutesRouteIdEditRoute,
  RoutesRouteIdIndexRoute: RoutesRouteIdIndexRoute,
}

const RoutesRouteIdRouteWithChildren = RoutesRouteIdRoute._addFileChildren(
  RoutesRouteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ErrorRoute: ErrorRoute,
  InitRoute: InitRoute,
  RoutesRouteIdRoute: RoutesRouteIdRouteWithChildren,
  RoutesNewRoute: RoutesNewRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
